---

- name: "Install Images directory"
  copy:
    src: Images
    dest: /opt/
    mode: 0777

- name: "Change folder permissions"
  shell: chmod 0777 /opt/Images

- name: "Setup Keyboard configuration"
  copy:
    src: configurations/keyboard
    dest: /etc/default/keyboard
    mode: preserve

# set timezone
- name: set timezone to Europe/Athens
  timezone:
    name: Europe/Athens

#lightdm
- name: "Setup Xorg configuration"
  copy:
    src: configurations/lightdm
    dest: /etc/lightdm
    mode: preserve

# Xorg
- name: "Setup Xorg configuration"
  copy:
    src: configurations/x11
    dest: /etc/x11

- name: "Setup Xresources configuration"
  copy:
    src: local_confingurations/.Xresources
    dest: /root/

# Bashrc
- name: "Setup Bashrc configuration"
  copy:
    src: local_confingurations/.bashrc
    dest: /root/.bashrc

- name: "Setup Bash Profile configuration"
  copy:
    src: local_confingurations/.bash_profile
    dest: /root/.bash_profile

# Config Dir
- name: "Setup config Directory"
  copy:
    src: local_confingurations/.config
    dest: /root/
    mode: preserve

