---

- name: Installing software-properties-common
  apt: 
     name: software-properties-common 
     update_cache: yes
     state: latest

- name: Installing build-essential
  apt: 
     name: build-essential
     state: latest
