---
- name: "Install Vim"
  apt:
     name: vim
     state: latest

- git:
    repo: 'https://github.com/amix/vimrc.git'
    dest: /opt/vim_runtime
    depth: 1

- name: "Copy Vim configuration"
  shell: cp -r /opt/vim_runtime /root/.vim_runtime
    
- name: "Install Vim"
  shell: /root/.vim_runtime/install_awesome_vimrc.sh
  ignore_errors: True
