---
- name: "Install Vim"
  apt:
     name: vim
     state: latest

- git:
    repo: 'https://github.com/amix/vimrc.git'
    dest: /opt/vim_runtime
    depth: 1

- name: "Copy Vim configuration"
  copy:
    src: /opt/vim_runtime
    dest: ~/.vim_runtime
    
- name: "Install Vim"
  shell: ~/.vim_runtime/install_awesome_vimrc.sh
  ignore_errors: True
