---

- name: "Creating screenshots Directory"
  shell: mkdir -p ~/Pictures/screenshots

- name: "Setup i3 configuration"
  copy:
    src: configurations/.i3
    dest: /root/

- name: "Setup irssi configuration"
  copy:
    src: configurations/.irssi
    dest: /root/

- name: "Setup fehbg configuration"
  copy:
    src: configurations/.fehbg
    dest: /root/

- name: "Setup zsh configuration"
  copy:
    src: configurations/.zshrc
    dest: /root/


- name: "Setup scripts Directory"
  copy:
    src: scripts
    dest: /opt/

