---
# tasks file for i3

- name: Installing suckless-tools
  apt:
     name: suckless-tools
     state: latest

- git:
    repo: 'https://github.com/Airblader/i3.git'
    dest: /opt/i3-gaps

- name: Pulls gaps from github
  shell: git checkout gaps && git pull
  args:
    chdir: /opt/i3-gaps/

- name: configure packages
  shell: autoreconf --force --install
  args:
    chdir: /opt/i3-gaps/

- name: Delete folder if exists
  shell: rm -rf build && mkdir -p  build
  args:
    chdir: /opt/i3-gaps/

- name: Prepare configuration
  shell: ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
  args:
    chdir: /opt/i3-gaps/build

- name: Compile
  shell: make
  args:
    chdir: /opt/i3-gaps/build

- name: Compile and install
  shell: make install
  args:
    chdir: /opt/i3-gaps/build

- git:
    repo: 'https://github.com/Airblader/i3blocks-gaps'
    dest: /opt/i3blocks

- name: Pulls i3blocks from github
  shell: git pull
  args:
    chdir: /opt/i3blocks

- name: make clean all for i3blocks
  shell: make clean all
  args:
    chdir: /opt/i3blocks

- name: Installing i3blocks
  shell: make install
  args:
    chdir: /opt/i3blocks

- name: Installing i3status
  apt:
     name: i3status
     state: latest

- name: Installing i3lock
  apt:
     name: i3lock
     state: latest

- name: Installing ranger
  apt:
     name: ranger
     state: latest

- name: Installing irssi
  apt:
     name: irssi
     state: latest

- name: Installing feh
  apt:
     name: feh
     state: latest

- name: Installing zsh
  apt:
     name: zsh
     state: latest

- name: Installing redshift
  apt:
     name: redshift
     state: latest

- name: Installing redshift-gtk
  apt:
     name: redshift-gtk
     state: latest

- name: setup xinit
  shell: echo 'exec i3' > /root/.xinitrc

- name: "Install i3ipc"
  shell: pip install i3ipc

- git:
    repo: 'https://github.com/ryanoasis/nerd-fonts.git'
    dest: /opt/nerd-fonts
  
- name: "Installing nerd-fonts"
  shell: ./install
  args:
    chdir: /opt/nerd-fonts/  
