---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

# echo deb http://ftp.debian.org/debian stretch-backports main contrib > /etc/apt/sources.list.d/stretch-backports.list
- apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main contrib
    state: present
    filename: stretch-backports

- name: apt-get update
  apt:
    update_cache: yes

- name: Get kernel header version
  shell: "uname -r;"
  register: headers
  ignore_errors: True

- debug: msg=linux-headers-{{ headers.stdout }}

- name: Install virtualbox-guest-dkms
  apt:
    name: virtualbox-guest-dkms
    default_release: stretch-backports

- name: Install virtualbox-guest-x11
  apt:
    name: virtualbox-guest-x11
    default_release: stretch-backports

- name: Install linux-headers-{{ headers.stdout }}
  apt:
    name: linux-headers-{{ headers.stdout }}
    default_release: stretch-backports
  when: headers is succeeded 